Controllers/SocialMediaController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Proje.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SocialMediaController : Controller
    {
        SocialMediaManager socialMediaManager = new SocialMediaManager(new EfSocialMediaDal());

        public IActionResult Index()
        {
            var values = socialMediaManager.TGetList();

            return View(values);
        }

        [HttpGet]
        public IActionResult AddSocialMedia()
        {
            ViewBag.v1 = "Add Social Media";
            ViewBag.v2 = "Social Medias";
            ViewBag.v3 = "Add Social Media";

            return View();
        }
        [HttpPost]
        public IActionResult AddSocialMedia(SocialMedia socialMedia)
        {
            ViewBag.v1 = "Add Social Media";
            ViewBag.v2 = "Social Medias";
            ViewBag.v3 = "Add Social Media";

            socialMediaManager.TAdd(socialMedia);

            return RedirectToAction("Index");
        }

        public IActionResult DeleteSocialMedia(int id)
        {
            var value = socialMediaManager.TGetById(id);
            socialMediaManager.TDelete(value);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditSocialMedia()
        {
            ViewBag.v1 = "Edit Social Media";
            ViewBag.v2 = "Social Medias";
            ViewBag.v3 = "Edit Social Media";

            return View();
        }
        [HttpPost]
        public IActionResult EditSocialMedia(SocialMedia socialMedia)
        {
            ViewBag.v1 = "Edit Social Media";
            ViewBag.v2 = "Social Medias";
            ViewBag.v3 = "Edit Social Media";

            socialMediaManager.TUpdate(socialMedia);

            return RedirectToAction("Index");
        }
    }
}

Views/SocialMedia/AddSocialMedia.cshtml
@model EntityLayer.Concrete.SocialMedia

@{
    ViewData["Title"] = "AddSocialMedia";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<form asp-action="AddSocialMedia" asp-controller="SocialMedia" method="post" class="form">
    <div class="form-group">
        <label for="Title" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name" placeholder="Name...">
    </div>
    <div class="form-group">
        <label for="Title" class="form-label">Url</label>
        <input type="text" class="form-control" asp-for="Url" placeholder="Url...">
    </div>
    <div class="form-group">
        <label for="Title" class="form-label">Icon</label>
        <input type="text" class="form-control" asp-for="Icon" placeholder="Icon...">
    </div>
    <div class="form-group">
        <label for="Title" class="form-label">Status</label>
        <input type="text" class="form-control" asp-for="Status" placeholder="Status...">
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
    <a class="btn btn-light" href="/SocialMedia/Index">Cancel</a>
</form>

Views/SocialMedia/EditSocialMedia.cshtml
@model EntityLayer.Concrete.SocialMedia

@{
    ViewData["Title"] = "EditSocialMedia";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<form asp-action="EditSocialMedia" asp-controller="SocialMedia" method="post" class="form">
    <div class="form-group">
        <label for="Title" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name" placeholder="Name...">
    </div>
    <div class="form-group">
        <label for="Title" class="form-label">Url</label>
        <input type="text" class="form-control" asp-for="Url" placeholder="Url...">
    </div>
    <div class="form-group">
        <label for="Title" class="form-label">Icon</label>
        <input type="text" class="form-control" asp-for="Icon" placeholder="Icon...">
    </div>
    <div class="form-group">
        <label for="Title" class="form-label">Status</label>
        <input type="text" class="form-control" asp-for="Status" placeholder="Status...">
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
    <a class="btn btn-light" href="/SocialMedia/Index">Cancel</a>
</form>

Views/SocialMedia/Index.cshtml
@model List<SocialMedia>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="row ">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Social Media</h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th> Name </th>
                                <th> Url </th>
                                <th> Icon </th>
                                <th> Status </th>
                                <th> Actions </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var value in Model)
                            {
                                <tr>
                                    <td>
                                        <img src="@value.Icon" alt="image" />
                                        <span class="pl-2">@value.Name</span>
                                    </td>
                                    <td>@value.Url</td>
                                    <td>@value.Icon</td>
                                    <td>@value.Status</td>
                                    <td>
                                        <a href="/SocialMedia/EditSocialMedia/@value.SocialMediaId" class="btn btn-outline-warning">Edit</a>
                                        <a href="/SocialMedia/DeleteSocialMedia/@value.SocialMediaId" class="btn btn-outline-behance">Delete</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <a asp-action="AddSocialMedia" class="btn btn-outline-behance">Add Social Media</a>
                </div>
            </div>
        </div>
    </div>
</div>