Controllers/SkillController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Proje.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SkillController : Controller
    {
        SkillManager skillManager = new SkillManager(new EfSkillDal());

        public IActionResult Index()
        {
            ViewBag.v1 = "Skill List";
            ViewBag.v2 = "Skills";
            ViewBag.v3 = "Skill List";

            var values = skillManager.TGetList();

            return View(values);
        }

        [HttpGet]
        public IActionResult AddSkill()
        {
            ViewBag.v1 = "Add Skill";
            ViewBag.v2 = "Skills";
            ViewBag.v3 = "Add Skill";

            return View();
        }
        [HttpPost]
        public IActionResult AddSkill(Skill skill)
        {
            skillManager.TAdd(skill);

            return RedirectToAction("Index");
        }

        public IActionResult DeleteSkill(int id)
        {
            var value = skillManager.TGetById(id);
            skillManager.TDelete(value);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditSkill(int id)
        {
            ViewBag.v1 = "Edit Skill";
            ViewBag.v2 = "Skills";
            ViewBag.v3 = "Edit Skill";

            var value = skillManager.TGetById(id);

            return View(value);
        }
        [HttpPost]
        public IActionResult EditSkill(Skill skill)
        {
            skillManager.TUpdate(skill);

            return RedirectToAction("Index");
        }
    }
}

Views/Skill/AddSkill.cshtml
@model EntityLayer.Concrete.Skill

@{
    ViewData["Title"] = "AddSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<form asp-action="AddSkill" asp-controller="Skill" method="post" class="form">
    <div class="form-group">
        <label for="Title" class="form-label">Skill Title</label>
        <input type="text" class="form-control" asp-for="Title" placeholder="Skill Title...">
    </div>
    <div class="form-group">
        <label for="Value" class="form-label">Skill Value</label>
        <input type="text" class="form-control" asp-for="Value" placeholder="Skill Value...">
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>

Views/Skill/EditSkill.cshtml
@model EntityLayer.Concrete.Skill

@{
    ViewData["Title"] = "EditSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<form asp-action="EditSkill" asp-controller="Skill" method="post" class="form">
    <div class="form-group">
        <label for="Title" class="form-label">Skill Title</label>
        <input type="text" class="form-control" asp-for="Title" placeholder=@Model.Title>
    </div>
    <div class="form-group">
        <label for="Value" class="form-label">Skill Value</label>
        <input type="text" class="form-control" asp-for="Value" placeholder=@Model.Value>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

Views/Skill/Index.cshtml
@model List<Skill>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<!-- Light table -->
<div class="table-responsive">
    <table class="table align-items-center table-flush">
        <thead class="thead-light">
            <tr>
                <th scope="col" class="sort" data-sort="name">#</th>
                <th scope="col" class="sort" data-sort="budget">Title</th>
                <th scope="col" class="sort" data-sort="status">Value</th>
                <th scope="col" class="sort" data-sort="completion">Edit</th>
                <th scope="col">Delete</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody class="list">
        <tbody class="list">
            @foreach (var value in Model)
            {
            <tr>
                <th>@value.SkillId</th>
                <td>@value.Title</td>
                <td>
                    <div class="d-flex align-items-center">
                        <span class="completion mr-2">@value.Value%</span>
                        <div>
                            <div class="progress">
                                <div class="progress-bar bg-success" role="progressbar" aria-valuenow="@value.Value%" aria-valuemin="0" aria-valuemax="100" style="width: @value.Value%;"></div>
                            </div>
                        </div>
                    </div>
                </td>
                <td><a href="/Skill/EditSkill/@value.SkillId" class="btn btn-success">Edit</a></td>
                <td><a href="/Skill/DeleteSkill/@value.SkillId" class="btn btn-danger">Delete</a></td>
            </tr>
            }
        </tbody>
    </table>
    <a href="@Url.Action("AddSkill")" class="btn btn-primary">Add New Skill</a>
</div>